#index:
#    path: /
#    controller: App\Controller\DefaultController::index
places:
  type: rest
  resource: App\Controller\PlaceController

prices:
  type: rest
  resource: App\Controller\PriceController

users:
  type: rest
  resource: App\Controller\UserController